env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
plugins: 
  - eslint-plugin-jest
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 0