name: 'Changes-test(eslint)'

on:
  push:
  pull_request:
  
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Run eslint
    - run: npm install
    - run: npx eslint .